### ISSUE TITLE
Reusable connection

### ISSUE THREAD

**Issue by alexproca** [albertosantini/node-rio#21]
Right now the connection to R server and implicitly the current session is short lived inside the scope of `sendAction(..)` method. I think it will be useful if we can create first a client `client = net.createConnection(netOpts)` then pass that client in the options to `evaluateWithEntryPoint(cmd, {"client": client, ....})` in order to get back the same session (variables, functions, etc.) in a subsequent call.

**Comment by sparkycrisse** [comment]
Hi @albertosantini, 

First of all: thx for creating this nice interface between Rserve and NodeJS!

I'm running this code in a Raspberry Pi environment. The overhead by constantly creating new (simultaneous) connections to the local Rserve instance causes the Pi to run out of memory quickly so in my case a persistent connection is needed. 

Yesterday evening I gave it a try to start on implementing the ability to send multiple commands to Rserve while keeping the connection open. It's still quick & dirty (plan to refactor and improve in the following weeks), but I would appreciate it if you could take a quick look and comment on possible improvements. Here's the link to the forked repo: [Forked Repo](https://github.com/Eventigrate/node-rio/blob/master/lib/rio.js)

Thanks!

**Comment by albertosantini** [comment]
@sparkycrisse Nice contribution!

It would be better to fork from `dev-2.x` branch. :)

And about the implementation would it be enough reusing `client` connection?
https://github.com/albertosantini/node-rio/blob/dev-2.x/lib/main.js#L15

Something like: 

```
var client = null;
function connect(netOpts, callback, isRecordMode) {
    var recordStream;

    if (!client) {
        client = net.createConnection(netOpts);
    }
...
```

**Comment by albertosantini** [comment]
`dev-2.x` is merged. 

Contribution is welcome, because, tt the moment, is not my main use case.
