### ISSUE TITLE
update NPM version

### ISSUE THREAD

**Issue by dltmd6262** [albertosantini/node-rio#32]
Hello,

Thank you guys for such a great package. Right now I'm using your source code because the package at npm seems to be pretty outdated. When are you planning on making another npm release?? will it be after your 2.x milestone??

**Comment by albertosantini** [comment]
Well, `1.4.0` is very solid. :)

`2.0.0` changes the interface (and the implementation is refactored), but there are not new features.
I would like to review a few details and then it is ready to publish (in a couple of weeks).

My suggestion is using the actual version. The upgrade is quite straightforward,

**Comment by dltmd6262** [comment]
Great :) I like the new interface but I will stick with 1.4.0 for now. Thanks alot!
